#!/usr/bin/env python3
"""
Download Google Fonts for self-hosting.
Produces local WOFF2 files + @font-face CSS for each family.
"""

import re
import os
import sys
import urllib.request
import concurrent.futures
from pathlib import Path

UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"

FAMILIES = {
    "NotoSansJP": {
        "url": "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;500;600;700;900&display=swap",
        "css_family": "Noto Sans JP",
    },
    "BeVietnamPro": {
        "url": "https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@400;500;600;700;900&display=swap",
        "css_family": "Be Vietnam Pro",
    },
}

FONTS_DIR = Path(__file__).parent


def fetch_css(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read().decode("utf-8")


def parse_font_faces(css: str):
    """Return list of dicts with keys: comment, weight, style, src_url, unicode_range."""
    # Split on @font-face blocks
    blocks = re.findall(
        r'(/\*[^*]*\*/)?\s*@font-face\s*\{([^}]+)\}',
        css,
        flags=re.DOTALL,
    )
    faces = []
    for comment, body in blocks:
        weight = re.search(r'font-weight:\s*(\d+)', body)
        style  = re.search(r'font-style:\s*(\S+)', body)
        url    = re.search(r'url\(([^)]+)\)', body)
        urange = re.search(r'unicode-range:\s*([^\n;]+)', body)
        if weight and url:
            faces.append({
                "comment":       comment.strip() if comment else "",
                "weight":        weight.group(1),
                "style":         style.group(1) if style else "normal",
                "src_url":       url.group(1).strip().strip("'\""),
                "unicode_range": urange.group(1).strip() if urange else "",
            })
    return faces


def download_one(args):
    url, dest = args
    if dest.exists():
        return dest, False  # skip
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        dest.write_bytes(r.read())
    return dest, True


def process_family(name: str, meta: dict):
    dest_dir = FONTS_DIR / name
    print(f"\n[{name}] Fetching CSS …")
    css = fetch_css(meta["url"])

    faces = parse_font_faces(css)
    print(f"[{name}] Found {len(faces)} @font-face blocks")

    # Build download list + local filenames
    tasks = []
    for i, f in enumerate(faces):
        ext = ".woff2" if "woff2" in f["src_url"] else ".woff"
        local_name = f"{name}-w{f['weight']}-{i:04d}{ext}"
        f["local_file"] = local_name
        tasks.append((f["src_url"], dest_dir / local_name))

    # Download in parallel
    print(f"[{name}] Downloading {len(tasks)} files …")
    downloaded = 0
    skipped = 0
    with concurrent.futures.ThreadPoolExecutor(max_workers=20) as ex:
        for dest, was_new in ex.map(download_one, tasks):
            if was_new:
                downloaded += 1
            else:
                skipped += 1
    print(f"[{name}] done — {downloaded} downloaded, {skipped} skipped")

    # Generate @font-face CSS with local paths
    lines = []
    lines.append(f"/* Self-hosted {meta['css_family']} — generated by download_fonts.py */")
    for f in faces:
        local_path = f"{name}/{f['local_file']}"
        block = f"{f['comment']}\n" if f["comment"] else ""
        block += "@font-face {\n"
        block += f"  font-family: '{meta['css_family']}';\n"
        block += f"  font-style: {f['style']};\n"
        block += f"  font-weight: {f['weight']};\n"
        block += "  font-display: swap;\n"
        block += f"  src: url(\"{local_path}\") format('woff2');\n"
        if f["unicode_range"]:
            block += f"  unicode-range: {f['unicode_range']};\n"
        block += "}"
        lines.append(block)

    css_out = FONTS_DIR / f"{name.lower().replace('_', '-')}.css"
    css_out.write_text("\n\n".join(lines) + "\n", encoding="utf-8")
    print(f"[{name}] CSS written → {css_out.relative_to(FONTS_DIR.parent.parent)}")
    return css_out


if __name__ == "__main__":
    for name, meta in FAMILIES.items():
        process_family(name, meta)

    print("\nAll done. Link the generated CSS files in your HTML:")
    print('  <link rel="stylesheet" href="fonts/notosansjp.css">')
    print('  <link rel="stylesheet" href="fonts/bevietnampro.css">')
